### ISSUE TITLE
Slider seems to render outside it bounds

### ISSUE THREAD

**Issue by cjh1** [Kitware/eSimMon#236]
![screen](https://user-images.githubusercontent.com/1031053/204909169-e9b425f2-2ca5-4f19-a395-3b7bd46c0515.png)

**Comment by bnmajor** [comment]
@cjh1 This is with the latest changes on master? This should have been fixed in [f96f6d6](https://github.com/Kitware/eSimMon/pull/234/commits/f96f6d61e0b42c2572b1852f4b1df247776dd2f4)

**Comment by cjh1** [comment]
@bnmajor no, was testing #235, I will try with master, thanks.

**Comment by cjh1** [comment]
This is indeed fixed in master, thanks @bnmajor
