### ISSUE TITLE
Clean up security alerts

### ISSUE THREAD

**Issue by cjh1** [Kitware/eSimMon#68]

**Comment by cjh1** [comment]
https://github.com/Kitware/eSimMon/network/alerts

**Comment by bnmajor** [comment]
@cjh1 This link gives me a 404 error, is there another way I can access this alert to see what the problem is?

**Comment by cjh1** [comment]
Sorry, I added you to the appropriate list, you should be able to see them now.

**Comment by bnmajor** [comment]
Fixed in #70
